### ISSUE TITLE
/f claimat doesn't work

### ISSUE THREAD

**Issue by Kira07** [ProSavage/SavageFactions#247] opened 2019-11-04 19:01 UTC
**Describe the bug**
When I try to claim with /f map it always says that I don't have permission even when I am the faction leader and even with /f bypass enabled, I have the factions.claimat permission and the permission to claim (/f claim works).

**To Reproduce**
1. Do /f map
2. Click on a chunk to try and claim it
3. Look at your chat
4. See error message

**Expected behavior**
It should claim the chunk.

**Server VErsion (please complete the following information):**
 - Spigot Version: Paperspigot 1.8.8
 - Factions Version: 1.6.9.5-U0.2.1-RC-1.6.2-RC-2.5-RC-7

**Comment by Drc-DEV** [comment] 2019-12-01 05:28
Can't reproduce, maybe it got fixed in one of the latest commits somewhere. Open a new ticket if this is still an issue on the latest build.

**Closed as completed by Drc-DEV** 2019-12-01 05:28 UTC
Labels: bug
