### ISSUE TITLE
Mobs still spawning in faction (help!)

### ISSUE THREAD

**Issue by maikyjolling** [ProSavage/SavageFactions#194] opened 2019-07-27 20:35 UTC
**Describe the bug**
There is a problem with the factions that have mobs spawning into them. I think this is a bug. 

**Screenshots**

**Server VErsion (please complete the following information):**
 - Spigot Version: 1.14.3
 - Factions Version Latest
 - Minecraft Version: 1.14.3

**Comment by ElapsedDev** [comment] 2019-08-22 05:00
Please explain more to this bug you speak off!

**Comment by Savag3life** [comment] 2019-09-26 13:02
I'm going to close this issue as it has been more than a month without a reply from the reporter. If the issue is still persistent in the lastest build please reopen this issue.

Thanks, Illyria Team

**Closed as completed by Savag3life** 2019-09-26 13:02 UTC
Labels: bug
